blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('search/', views.post_search, name='post_search'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('training/', views.training, name='training'),
    path('consultancy/', views.consultancy, name='consultancy'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post_detail'),
    path('<int:id>/share/', views.post_share, name='post_share'),
]

ethiopython/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User


# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    BLOG_STATUS = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(
        max_length=10, choices=BLOG_STATUS, default='draft')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail",
                       args=[
                           self.publish.year,
                           self.publish.month,
                           self.publish.day,
                           self.slug,
                       ])


class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    body = models.TextField()
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class PostEmailShareForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=250)
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    message = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.postgres.search import SearchVector
from taggit.models import Tag
from .forms import PostEmailShareForm, PostCommentForm, ContactForm
from .models import Post, Comment

# Create your views here.


def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html',
                  {'posts': posts, 'page': page, 'tag': tag})


def post_detail(request, year, month, day, slug):

    post = get_object_or_404(Post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=slug,
                             status='published')

    comments = post.comments.filter(is_active=True)
    new_comment = None
    if request.method == "POST":
        comment_form = PostCommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = PostCommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    related_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    related_posts = related_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:3]

    return render(request, 'blog/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'related_posts': related_posts,
                   })


def post_share(request, id):
    post = get_object_or_404(Post, id=id, status='published')
    sent = False
    if request.method == 'POST':
        form = PostEmailShareForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'ephremwube@gmail.com', [cd['to']])
            sent = True
    else:
        form = PostEmailShareForm()
    return render(request, 'blog/post_share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    query = request.GET.get('query', '')
    results = Post.published.annotate(
        search=SearchVector('title', 'body'),).filter(search=query)
    return render(request, 'blog/search.html', {'query': query, 'results': results})


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    sent = False
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            send_mail(
                cd['subject'],
                cd['message'],
                cd['email'],
                ['ephremwube@gmail.com'],
            )
            return HttpResponseRedirect('/contact?sent=True')

    else:
        form = ContactForm()
        if 'sent' in request.GET:
            sent = True
    return render(request, 'blog/contact.html', {'form': form, 'sent': sent})


def training(request):
    return render(request, 'blog/training.html')


def consultancy(request):
    return render(request, 'blog/consultancy.html')

blog/templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- css -->
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>{% block title %}{% endblock %} | ethiopython</title>
</head>

<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark text-uppercase fs-5">
        <div class="container-fluid">
            <a class="navbar-brand fs-4" href="{% url 'blog:post_list' %}">EthioPython</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:training' %}">Training</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:consultancy' %}">Consulting</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
                    </li>
                </ul>
                <form action="{% url 'blog:post_search' %}" method="get" class="d-flex col-lg-6">
                    <input class="form-control me-2 fs-5 mt-2" type="search" name="query" placeholder="SEARCH POSTS..."
                        aria-label="Search">
                    <button class="btn btn-outline-light text-uppercase fs-5 mt-2" type="submit">SEARCH
                    </button>
                </form>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}


    <!-- footer -->
    <div class="container my-5 py-5">

    </div>
    <footer class="text-light text-center text-lg-start pt-5 mt-5">
        <div class="container p-5">
            <div class="row text-light">
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Footer Content</h5>
                    <p>
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                        molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                        voluptatem veniam, est atque cumque eum delectus sint!
                    </p>
                </div>

                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Get to know us</h5>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="{% url 'blog:training' %}" class="text-white">Training</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:contact' %}" class="text-white">Contact</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase mb-0">Newsletter</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="{% url 'blog:about' %}" class="text-white">About</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:consultancy' %}" class="text-white">Consultancy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>

        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2021 Copyright:
            <a class="text-white" href="#">ethiopython.com</a>
        </div>
    </footer>


    <!-- bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <script src="{% static 'scripts.js' %}"></script>
</body>

</html>

blog/templates/blog/consultancy.html
{% extends 'base.html'%}
{% load static %}
{% block title %}Consultancy{% endblock%}

{% block content %}

<div class="container text-center text-uppercase mt-5">
    <h1 class="display-3 mb-3">Consultancy</h1>
</div>
<div class="container py-5 my-5">
    <p class="lead my-3">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut neque ducimus eveniet, numquam quod iure minima est
        vel? Placeat possimus quas minima fugit iure laborum praesentium alias, asperiores velit aspernatur ratione
        error temporibus explicabo exercitationem a modi aliquid quaerat quibusdam eum ab veniam tempora iusto, nemo
        dolores? Saepe error dignissimos inventore impedit ea et molestias reprehenderit. Quasi fuga, nulla quisquam
        blanditiis officia repellendus, velit itaque dignissimos qui at distinctio. Possimus, fugit suscipit.
        Recusandae, tenetur? Mollitia voluptatibus dolorum optio porro quia error dolor modi, velit voluptas cum, itaque
        eveniet amet repellat iusto quasi perferendis expedita a inventore maxime ad pariatur vitae dolore. Ducimus hic
        nemo eveniet veritatis veniam natus illo magnam earum fugiat, voluptatibus fugit? Odio minima non recusandae
        architecto quae quos ullam, commodi, tenetur expedita facilis dolor autem exercitationem eius ut dignissimos
        dicta id eligendi aut sint! Inventore quo architecto aliquid pariatur neque rem quae voluptate exercitationem
        et, dolorem, ad corporis omnis officiis unde ullam quisquam rerum vel beatae facilis quam. Dicta maiores fuga
        eius! Ab sequi, illo harum maxime veritatis, fugiat fuga sint expedita sit, maiores eum libero. Facilis ducimus
        expedita nulla officiis explicabo, aspernatur itaque, rem distinctio saepe hic quae consectetur? Voluptatem
        perferendis dolore dignissimos sint vero reprehenderit omnis consequatur, quisquam tempora totam consequuntur
        enim quaerat illum qui assumenda sequi commodi rem labore! Tempora nemo totam rerum repellat iste maiores.
        Harum, nisi odio! Consequatur, voluptate. Veniam quae ipsum tenetur saepe voluptatum labore eligendi nihil minus
        esse, vitae tempore est illum obcaecati qui. Excepturi, ullam doloremque assumenda incidunt qui, amet iusto
        voluptates ad, impedit itaque cum error vero placeat vel molestiae a commodi. Tenetur excepturi, iste iure animi
        quibusdam, eum nesciunt voluptates distinctio repudiandae commodi deleniti reiciendis dolore omnis eaque laborum
        labore ipsum veniam voluptate ab explicabo error! Molestiae repellat sunt sed libero, suscipit nobis voluptas,
        exercitationem quidem illo ipsum accusantium obcaecati iusto vitae voluptate officiis sint commodi tempora!
        Minima reiciendis iure architecto ea blanditiis voluptatibus dolore cum! Velit modi, voluptatem aliquam incidunt
        sunt exercitationem cupiditate qui perferendis. Doloribus aliquid nobis, debitis veritatis amet, officiis itaque
        perferendis animi placeat quae exercitationem, distinctio corporis rerum provident laudantium facere accusamus
        eius id accusantium sunt eum quis nesciunt dolore ullam? Aliquid, fugiat est voluptate ab reiciendis, illum rem
        autem expedita ut molestias, ad harum! Perspiciatis molestias minus, enim voluptatem aperiam repudiandae nemo
        blanditiis libero cupiditate dolorum earum odit autem esse reprehenderit, accusamus inventore perferendis ea
        eveniet porro corrupti. Deserunt delectus at nostrum!
    </p>
</div>
{% endblock %}

blog/templates/blog/contact.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Contact{% endblock%}

{% block content %}

<div class="container text-center text-uppercase mt-5 py-5">
    <h1 class="display-3 mb-3">Contact Us</h1>
</div>
{% if sent %}
<div class="container bg-success text-white m-auto col-lg-6 py-3 mb-5">
    <p class="lead text-center fs-4">Your message was submitted successfully</p>
</div>
{% else %}

<div class="container my-5 col-lg-9">
    <form action="" method="post" class="bg-light p-2">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" role="button" value="Contact Us" class="btn btn-lg btn-success">
    </form>
</div>
{% endif %}

{% endblock %}

blog/templates/blog/most_commented_posts.html
<div class="container mb-3">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in commented_posts %}
        <div class="col">
            <div class="card h-100 box shadow-lg mb-5 bg-body rounded">
                <div class="card-body">
                    <a href="{{ post.get_absolute_url }}" class="nav-link ps-0">
                        <h3 class="card-title fw-bold  text-dark">{{ post.title }}</h3>
                    </a>
                    {% for tag in post.tags.all %}

                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="pe-2 text-dark">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %} {% endif %}
                    {% endfor %}
                    <p class="card-text">{{ post.body|truncatewords:30|linebreaks }}
                        <a href="{{ post.get_absolute_url }}" class="card-link text-uppercase text-secondary">
                            read more
                        </a>
                    </p>

                </div>
                <div class="card-footer">
                    Published {{ post.publish }} by {{ post.author }}
                </div>

            </div>
        </div>
        {% empty %}
        <h1>No posts listed</h1>
        {% endfor %}
    </div>
</div>

blog/templates/blog/post_detail.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %}{{ post.title }}{% endblock%}

{% block content %}
<div class="container my-5 py-5 col-lg-9 shadow-lg p-3 mb-5 bg-body rounded">
    <div class="card">
        <div class=" card-header display-4 text-center text-capitalize">
            {{ post.title }}
        </div>
        <div class="card-body">
            <p class="card-text text-justify">{{ post.body }}</p>
            <p class="card-text text-justify">
                <a href="{% url 'blog:post_share' post.id %}" class="btn btn-lg btn-success">
                    Share
                </a>
            </p>
        </div>

        <div class="card-footer text-muted text-start">
            Published {{ post.publish }} By {{ post.author }}
        </div>
        {% with comments.count as total_comments %}
        <h3 class="my-3 ps-2">{{ total_comments }} comment {{ total_comments|pluralize }}</h3>
        {% endwith %}
        <div class="">
            {% if new_comment %}
            <h2 class="ps-2">Your comment has been added.</h2>
            {% else %}
            <h2 class="ps-2">Add a new comment</h2>
            <form method="post" class="p-2">
                {{ comment_form|crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg mb-2 ps-2">Add
                    Comment</button>
            </form>
            {% endif %}
        </div>
        {% for comment in comments %}
        <div class="row my-2">
            <div class="col-1 pe-2">
                <div class="ms-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor"
                        class="bi bi-person-bounding-box" viewBox="0 0 16 16">
                        <path
                            d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z" />
                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                    </svg>
                </div>

            </div>
            <div class="col-9">
                <p>
                    <span class="text-danger text-capitalize lead me-2">{{ comment.name }}</span>
                    {{ comment.created_at }}
                </p>
                <p class="lead">{{ comment.body|linebreaks }}</p>
            </div>
        </div>
        {% empty %}
        <p class="lead py-2 my-2 ps-2">There are no comments yet</p>
        {% endfor %}
    </div>

</div>

<!-- related posts -->
{% if related_posts %}
<div class="container my-5">
    <h1 class="text-center text-uppercase display-2 pb-2">Related Posts</h1>
</div>
<div class="container mb-3">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in related_posts %}
        <div class="col">
            <div class="card h-100 shadow-lg mb-5 bg-body rounded">
                <div class="card-body">
                    <a href="{{ post.get_absolute_url }}" class="nav-link ps-0">
                        <h3 class="card-title fw-bold text-dark">{{ post.title }}</h3>
                    </a>
                    <p class="card-text">{{ post.body|truncatewords:30|linebreaks }}
                        <a href="{{ post.get_absolute_url }}" class="card-link text-uppercase text-dark">
                            read more
                        </a>
                    </p>
                </div>
                <div class="card-footer">
                    Published {{ post.publish }} by {{ post.author }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="container text-center">
    <p class="lead fs-3">No Related Posts</p>

</div>
{% endif %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html'%}
{% load blog_tags %}
{% load static %}
{% block title %}Home{% endblock%}

{% block content %}
<!-- banner image -->

<section id="banner">
    <div class="container">
        <div class="row">
            <div class="col-md-6 pt-4">
                <h1 class="display-3 text-uppercase fw-bolder pt-5">Learn Python</h1>
                <p class="font-monsopace fs-5 my-3">
                    Python is a general-purpose programming language that’s powerful yet easy to read, making it a great
                    first language to learn. From web development to machine learning to data science — Python can do it
                    all.
                </p>
            </div>
            <div class="col-md-6 text-center">
                <img src="{% static 'images/man-computer.png' %}" class="img-fluid" alt="">
            </div>
        </div>
    </div>
    <img src="{% static 'images/wave1.png' %}" class="bottom-img" alt="">
</section>


<!-- post-list -->
<div class="container text-center text-uppercase mt-5">
    <h1 class="display-3 mb-3">Latest Posts</h1>
</div>
<div class="container mb-3">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in posts %}
        <div class="col">
            <div class="card h-100 shadow-lg mb-5 bg-body rounded">
                <div class="card-body">
                    <a href="{{ post.get_absolute_url }}" class="nav-link ps-0">
                        <h3 class="card-title fw-bold  text-dark">{{ post.title }}</h3>
                    </a>
                    {% for tag in post.tags.all %}

                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="pe-2 text-dark">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %} {% endif %}
                    {% endfor %}
                    <p class="card-text">{{ post.body|truncatewords:30|linebreaks }}
                        <a href="{{ post.get_absolute_url }}" class="card-link text-uppercase text-secondary">
                            read more
                        </a>
                    </p>

                </div>
                <div class="card-footer">
                    Published {{ post.publish }} by {{ post.author }}
                </div>

            </div>
        </div>
        {% empty %}
        <h1>No posts listed</h1>
        {% endfor %}
    </div>
    {% include "pagination.html" with page=posts %}
</div>
<div class="container-fluid my-5 p-4" id="summary">
    <h5 class="display-5 text-uppercase text-center">Summary</h5>
    <div class="row m-auto col-lg-5 text-center py-3">
        <div class="col-6">
            <div class="py-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                    class="bi bi-stickies-fill" viewBox="0 0 16 16">
                    <path d="M0 1.5V13a1 1 0 0 0 1 1V1.5a.5.5 0 0 1 .5-.5H14a1 1 0 0 0-1-1H1.5A1.5 1.5 0 0 0 0 1.5z" />
                    <path
                        d="M3.5 2A1.5 1.5 0 0 0 2 3.5v11A1.5 1.5 0 0 0 3.5 16h6.086a1.5 1.5 0 0 0 1.06-.44l4.915-4.914A1.5 1.5 0 0 0 16 9.586V3.5A1.5 1.5 0 0 0 14.5 2h-11zm6 8.5a1 1 0 0 1 1-1h4.396a.25.25 0 0 1 .177.427l-5.146 5.146a.25.25 0 0 1-.427-.177V10.5z" />
                </svg>
            </div>
            <p class="lead">{% total_posts %}</p>
            <p class="lead text-uppercase">Total Posts</p>
        </div>
        <div class="col-6">
            <div class="py-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                    class="bi bi-chat-left-dots-fill" viewBox="0 0 16 16">
                    <path
                        d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm5 4a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                </svg>
            </div>
            <p class="lead">{% total_comments %}</p>
            <p class="lead text-uppercase">Total Comments</p>
        </div>
    </div>
</div>

<h3 class="my-2 py-2 display-4 lead text-center text-uppercase">Most commented Posts</h3>
{% most_commented_posts %}




{% endblock %}

blog/templates/blog/post_share.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Share a post{% endblock%}

{% block content %}
{% if sent %}
<div class="container text-center m-auto my-5 py-5 col-lg-7">
    <p class="lead fw-bold bg-success text-white py-2">E-mail successfully sent to {{ form.cleaned_data.to }}</p>

    <div class="container" style="height: 200px;">

    </div>
</div>


{% else %}
<div class="container m-auto my-5 py-3 col-lg-7">
    <h2 class="text-center p-2 mb-3 bg-light">Share "{{ post.title }}" by e-mail</h1>
        <form method="post" class="bg-light">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-lg btn-success mb-2">Send an e-mail</button>
        </form>
</div>
{% endif %}
{% endblock %}